#import "/Templates/generic.typ": latex
#import "/Templates/notes.typ": chapter_heading
#import "@preview/ctheorems:1.1.0": *
#import "/Templates/math.typ": *
#show: latex
#show: chapter_heading
#show: thmrules
#show: symbol_replacing
//#show: equation_references
//#show: equation_numbering
#set pagebreak(weak: true)
#set page(margin: (x: 2cm, top: 2cm, bottom: 2cm), numbering: "1")
#set enum(numbering: "(1)", indent: 1em)
#set heading(supplement: "Lecture")

#show heading: it => {
  if (it.numbering == none or it.level > 1) {
    return it
  }
  let numbers = counter(heading).at(it.location())
  let body = it.body
  block([*#body*])
}
#outline()

= Lecture 1
Let $Omega$ be an open set in $RR^(n+1)$ and let $V$ be a compactly supported vector field on $Omega$. Let $Phi_t^V : Omega -> Omega$ be the flow generated by $V$.

Now let $Sigma$ be a hypersurface in $Omega$ and assume that $iota : Sigma -> Omega$ is proper. We say that $Sigma$ is minimal if
$
d / (d t) Area(Phi_t^V (Sigma)) = 0
$
for any admissable $V$ as above.

In other words, $Sigma$ is a critical point of the area functional.
One can check that
$
d / (d t) Area(Phi_t^V (Sigma)) = integral_Sigma div_Sigma V dif mu
$
where at any point $p$, $div_Sigma V = sum_(i = 1)^n D_(e_i) V dot e_i$ for any orthonormal frame centered at $p$.

Now we have
$
integral_Sigma div_Sigma V dif mu = integral_Sigma div_Sigma (V^top + V^perp)
= integral_Sigma div_Sigma V^top
+ integral_Sigma div_Sigma V^perp
= integral_Sigma div_Sigma V^perp
$
since the first integral vanishes by divergence theorem.

On the other hand we have
$
div_Sigma V^perp = div_Sigma ((V dot nu) nu) = sum_i^n (D_e_i nu dot e_i) (
  V dot nu
) = - arrow(H)_Sigma dot V
$
so $Sigma$ is minimal if and only if $arrow(H)_Sigma = 0$.

== Monotonicity of Area Ratios
Assume that $Sigma$ is a proper minimal hypersurface in $Omega seq RR^(n+1)$, we will call
$
Psi_(Sigma,x_0) (R) = (|Sigma sect B_R (x_0)|) / (R^n)
$
the _area ratio_, and its importance is due to its Monotonicity:

For $R_2 > R_1$
$
Psi_(Sigma, x_0) (R_2) - Psi_(Sigma, x_0) (R_1) = integral_(B_R_2 (
  x_0
) backslash B_R_1 (x_0) sect Sigma) (|(x-x_0)^perp|^2) / (|x-x_0|^(n+2))
$
as long as $ov(B_R_2 (x_0)) seq Omega$.

In particular, if $Psi_(Sigma, X_0) (R)$ is independent of $R$ then $(x - x_0)^perp = 0$ in $Sigma$, which is equivalent to $Sigma$ being a cone with vertex at $x_0$.

Let $rho_i -> infinity$ and $Sigma_i = rho_i (Sigma - x_0)$, clearly $Sigma_i$ is also a minimal hypersurface. Then up to passing to a subsequence, this sequence converges weakly (in the sense of measures) to a hypersurface $Sigma_infinity$ which is minimal in $RR^n$ and
$
Psi_(Sigma_infinity, 0) (R)
= lim_(i -> infinity) Psi_(Sigma_i, 0) (R)
= lim_(i -> infinity) Psi_(Sigma, x_0) (rho_i^(-1) R)
$
which always exists and is independent of $R$, so $Sigma_infinity$ is a minimal cone.

The density of a minimal cone $phi$ is defined by
$
Theta(phi) := Psi_(phi, 0) (1) omega_n^(-1)
$
where $omega_n$ is the volume of a ball in $RR^n$. This normalization is picked so that $Theta(RR^n) = 1$.

#lemma[
  The hyperplane $RR^n$ minimizes density, in the sense that
  $
  Theta(Sigma) >= 1
  $
  for all hypersurfaces $Sigma$, and equality holds iff $Sigma$ is a hyperplane.
]
#exercise[
  Prove this.
]

A natural question then is, which minimal cone has the second least density?
It is non obvious that such a cone exists, but in fact we have a regularity theorem that implies this.
#theorem("Allard's Regularity")[
  There's an $epsilon(n) > 0$ so that if $C$ is a minimal cone in $RR^(n+1)$ and if $C != RR^n$ then
  $
  Theta(C) > 1 + epsilon.
  $
]

Now an important characterization of minimal cones is the following.
#lemma[
  If $C$ is a minimal cone iff the link $L(C) = C sect S^n$ is a minimal hypersurface in $S^n$.
]
This gives us a natural family of minimal cones arising from the family of minimal hypersurfaces in $S^n$, called the Clifford Tori, defined as
$
Gamma_(m,ell) = S^n (sqrt(m/(m + ell))) times S^n (sqrt(ell/(m + ell))).
$

#conjecture("Solomon")[
  The minimal cones $C_(m, ell)$ which are the cones over $Gamma_(m, ell)$, minimize the density of non-flat minimal cones.
]<conj-solomon>

The density of these cones is given by
$
Theta(C_(m, ell)) = (sigma_m sigma_ell) / (sigma_(m + ell)) (
  m / (m+ell)
)^(m / 2) (ell / (m+ell))^(ell / 2)
$
where $sigma_k$ is the volume of a unit $k$-sphere.

One can check that $lim_(ell "or" m -> infinity) Theta(C_(m, ell)) = sqrt(2)$.

@conj-solomon is true for $n = 3$.

By a result of Almgren, If $C seq RR^4$ is a minimal cone with $L(C)$ a smooth embedded surface of genus $0$ then $C = RR^3$.

By a result of Marques–Neves, in the other case we have $Theta(C) >= Theta(C_(1,1)) = pi/2$, equality if and only if $C = C_(1,1)$

= Lecture 2
We will now start exploring the connection between minimal cones and mean curvature flow, first notice that minimal cones are static solutions to mean curvature flow.

Another important property of minimal cones is that the density we defined earlier coincides with the limit of Gaussian area introduced in the other lecture. In fact to better get a handle on this area we can also define the Colding-Minicozzi entropy
$
lambda(Sigma) = sup_(x_0 in RR^(n+1), t_0>0)
(4pi t_0)^(- n / 2) integral_sigma e^(- (|x-x_0|^2) / (4 t_0)) dif mu (x)
$

#proposition[
  + For any hypersurface we have $lambda(Sigma) >= 1$
  + For any $y in RR^(n+1)$ we have $lambda(Sigma + y) = lambda(Sigma)$.
  + $lambda(Sigma times RR) = lambda(Sigma)$.
  + If $t |-> Sigma_t$ is a MCF then $t -> lambda(Sigma_t)$ is non-increasing.
]

A hypersurface $sigma$ is called a self-shrinker if $arrow(H)_sigma + x^perp/2 = 0$. Any minimal cone is a self-shrinker. The hyperplane, spheres and cylinders are all self-shrinkers. Angenent's torus and min-max shrinkers are other examples.

We also construct them by desingularization.

#theorem[
  The entropy stable shrinkers are $RR^n, S^n, S^r times RR^(n - r)$.
]
= Lecture 3
We will now begin discussing asymptotically conical shrinkers. These are MCFs with $M_t = sqrt(-t) Sigma$ and $M_t -> C$ as $t -> 0$ where $C$ is a cone.

The first thing we want to think is how to continue the flow at $t = 0$. We will define $Gamma_tau = 1/(sqrt(t)) Sigma_t$ where $tau = log t$ and we have
$
(diff_tau X)^perp = H_(Gamma_tau) - x^perp / 2.
$<eqn-rescaled_mcf>
This is in fact the gradient flow for
$
E(Gamma) = integral_Gamma e^((|x|^2) / 4)
$
and the critical points of $E$ are static solutions to the evolution equation above, namely
$
H_(Gamma_t) - x^perp / 2 = 0.
$
Such solutions are called expanders. Clearly every minimal cone is an expander.

#remark[
  There do not exist any compact expanders, one can see this by deriving the equation for $x^2$ (??) on an expander and apply maximum principle.
]

#theorem("Bernstein-W")[
  There's an open set of cones in $RR^3$ so that for each cone $C$ in the set there are at least 3 expanders asymptotic to $C$.
]

#theorem("Ding-Ilmanen")[
  For $n <= 6$, given a cone $C seq RR^(n+1)$ with smooth embedded link, there is an expander asymptotic to $C$.
]

#theorem[
  For $n <= 6$, given a minimal cone $C$ with smooth embedded link, there are two expanders $Sigma_+$ and $Sigma_-$ both asymptotic to $C$ lying on either side of $C$, and both have a sign.
]
#remark[
  Since they both have a sign, and since they both have
  $
  x^perp / 2 = H_(Sigma_(plus.minus))
  $
  then they are both radial over a sphere.
]
