#import "/Templates/generic.typ": latex, header
#import "@preview/ctheorems:1.1.0": *
#import "/Templates/math.typ": *
#import "/Templates/assignment.typ": *
#show: doc => header(title: "Assignment 4", name: "Jacob Reznikov", doc)
#show: latex
#show: NumberingAfter
#show: thmrules
#let col(x, clr) = text(fill: clr)[$#x$]
#let pb() = {
  pagebreak(weak: true)
}
#set page(numbering: "1")
#let bar(el) = $overline(#el)$
#set enum(numbering: "(a)")
// #show math.equation: set text(font: "Latin Modern Math")

*Sources consulted* \
Classmates: Frank Wang, Michael Panner, Julia Meng. We discussed essentially every single problem together.\
Texts: Class Notes, Algebraic Number Theory by Milne, Elementry and Analytic Theory of Algebraic Numbers by Narkiewicz, Number Fields by Marcus.

#let r5 = $#h(-2pt) root(3,5)$
= Question
== Statement
Let $K = QQ(r5)$
+ Prove that $cal(O)_K = ZZ[r5]$.
+ Factor the primes $p = 2,3,5,7,11,13$ in $QQ(r5)$. Write the prime ideals $frak(q)$ appearing in your factorization in the form $(p, f(r5))$ where $f in ZZ[x]$ has degree at most $3$.
+ Prove that the factorization patterns you found in $(b)$ represent every possible case; that is, every possible sum $[K : QQ] = sum_(frak(q) divides (p)) e_frak(q) f_(frak(q))$ that can arise for this particular field $K$. You should find that there is one numerically possible case that does not occur for $p <= 13$; you need to prove that it cannot occur for any prime $p$.
+ Find a different cubic field of the form $K = QQ(#h(-1pt) root(3,n))$ for which the one factorization pattern missing from $(c)$ does occur (demonstrate this explicitly).
== Solution
Set $alpha = root(3,5)$.
+ It is easy to see that the discriminant of $(1,alpha, alpha^2)$ is $-775 = -3^3 5^2$. Since $x^3 - 5$ is Eisenstein with $p = 5$ then we get that the true discriminant does include $5^2$ as a factor. Then we have $(x+5)^3 - 5 = x^3 + 15 x^2 + 75 x + 120$ which is Eisenstein with $p = 3$ so the true discriminant shares the factor $3^3$ and thus is indeed $-775$, hence $(1,alpha,alpha^2)$ is a basis and thus $cal(O)_K = ZZ[alpha]$.
+ Since $cal(O)_k = ZZ[alpha] iso ZZ[x] quo (x^3 - 5)$, we can reduce the question of is $frak(p)$ prime to asking if $cal(O)_k quo frak(p)$ is an integral domain. Since $frak(p)$ will contain the desired ideal $(p)$ we have that 
  $
  cal(O)_k quo frak(p) iso (cal(O)_k quo (p)) quo (frak(p) quo (p))
  $
  and hence it is enough to check that $frak(p)$ is prime in $FF_p [x] quo (x^3 - 5)$, which is equivalent to checking that it is generated by an irreducible polynomial, this gives us the following prime decompositions.
  $
    (2) = (2,alpha+1)(2, alpha^2 + alpha + 1)\
    (3) = (3,alpha+1)^3\
    (5) = (5,alpha)^3\
    (7) = (7)\
    (11) = (11, alpha+3)(11, alpha^2 + 3 alpha + 9)\
    (13) = (13, alpha+2)(13, alpha + 5)(13, alpha + 6)\
  $
+ The only decomposition that does not occur in this list is $(p) = X^2 Y$ for $X,Y$ prime ideals, let us assume that such a decomposition exists, then in our framework $X$ and $Y$ correspond to ideals of $FF_p [x] quo (x^3-5)$ which are all of degree 1, so are generated by linear elements. In other words, $X = (x - a), Y = (x - b)$. We thus have
  $
    (x-a)^2 (x-b)
    =
    (x^2 - 2 a x + a^2) (x - b)
    =
    x^3 - 2 a x^2 - b x^2 + a^2 x + 2 a b x - a^2 b
    \
    = x^3 + (-2a - b) x^2 + (a^2 + 2 a b) x - a^2 b
  $
  and so we have the following equivalences
  $
    -2a - b equiv 0 mod p
    quad
    a(a + 2b) equiv 0 mod p
  $
  and so we can now solve these equivalences. If $a equiv 0$ then we have $b equiv 0$ so we do not have distinct roots. We can thus assume that $a$ is invertible so $a + 2b equiv 0 mod p$ and also $2 a + b equiv 0 mod p$ and thus we have $a + 2 b - (4 a + 2 b) = - 3 a equiv 0 mod p$ so $a equiv 0$ and then again $b equiv 0$. We thus have a full contradiction and so such a decomposition cannot exist.
+ We set $alpha = root(3,10)$ and consider the number field $K = QQ(alpha)$, note that the following is an integral element of $cal(O)_K$
  $
    beta = (1 + alpha + alpha^2)/3
  $
  because
  $
    beta^3 - beta^2 - 3 beta - 3 = 0
  $
  and we have that the trace matrix looks like
  $
    mat(3,1,7;1,7,19;7,19,43)
  $
  so the discriminant is $Delta(1,beta,beta^2) = -300$, which factors as $-5^2 dot 3 dot 2^2$. But we know that the true discriminant shares the 2 and 5 factors because $x^3 - 10$ is Eisenstein with $p = 2$ and $p = 5$. We thus have $cal(O)_k = ZZ[x] quo (x^3 - x^2 - 3x - 3)$. Now in this ring we consider the prime ideal $(3)$ and we find using our usual technique that $x^3 - x^2 - 3x - 3 equiv x^2 (x - 1) mod 3$ so
  $
    (3) = (3, beta)^2 (3, beta - 1)
  $
  is the prime decomposition we were missing.

= Question
== Statement
Fo every ideal $frak(p)$ of $cal(O)_K$, show that there exists an order $A = ZZ[theta] seq cal(O)_K$ such that its conductor (defined as the ideal ${c in cal(O)_K : c cal(O)_K seq A }$) is coprime to $frak(p)$.
== Solution
We have $NN(I) = n$ for some integer $n$ and thus 
