#import "/Templates/generic.typ": latex, header
#import "@preview/ctheorems:1.1.0": *
#import "/Templates/math.typ": *
#import "/Templates/assignment.typ": *
#show: doc => header(title: "Assignment 4", name: "Jacob Reznikov", doc)
#show: latex
#show: NumberingAfter
#show: thmrules
#let col(x, clr) = text(fill: clr)[$#x$]
#let pb() = {
  pagebreak(weak: true)
}
#set page(numbering: "1")
#let bar(el) = $overline(#el)$
#set enum(numbering: "(a)")
// #show math.equation: set text(font: "Latin Modern Math")

*Sources consulted* \
Classmates: Frank Wang, Michael Panner, Julia Meng. We discussed essentially every single problem together.\
Texts: Class Notes, Algebraic Number Theory by Milne, Elementry and Analytic Theory of Algebraic Numbers by Narkiewicz, Number Fields by Marcus.

#let r5 = $#h(-2pt) root(3,5)$
= Question
== Statement
Let $K = QQ(r5)$
+ Prove that $cal(O)_K = ZZ[r5]$.
+ Factor the primes $p = 2,3,5,7,11,13$ in $QQ(r5)$. Write the prime ideals $frak(q)$ appearing in your factorization in the form $(p, f(r5))$ where $f in ZZ[x]$ has degree at most $3$.
+ Prove that the factorization patterns you found in $(b)$ represent every possible case; that is, every possible sum $[K : QQ] = sum_(frak(q) divides (p)) e_frak(q) f_(frak(q))$ that can arise for this particular field $K$. You should find that there is one numerically possible case that does not occur for $p <= 13$; you need to prove that it cannot occur for any prime $p$.
+ Find a different cubic field of the form $K = QQ(#h(-1pt) root(3,n))$ for which the one factorization pattern missing from $(c)$ does occur (demonstrate this explicitly).
== Solution
Set $alpha = root(3,5)$.
+ It is easy to see that the discriminant of $(1,alpha, alpha^2)$ is $-775 = -3^3 5^2$. Since $x^3 - 5$ is Eisenstein with $p = 5$ then we get that the true discriminant does include $5^2$ as a factor. Then we have $(x+5)^3 - 5 = x^3 + 15 x^2 + 75 x + 120$ which is Eisenstein with $p = 3$ so the true discriminant shares the factor $3^3$ and thus is indeed $-775$, hence $(1,alpha,alpha^2)$ is a basis and thus $cal(O)_K = ZZ[alpha]$.
+ Since $cal(O)_k = ZZ[alpha] iso ZZ[x] quo (x^3 - 5)$, we can reduce the question of is $frak(p)$ prime to asking if $cal(O)_k quo frak(p)$ is an integral domain. Since $frak(p)$ will contain the desired ideal $(p)$ we have that 
  $
  cal(O)_k quo frak(p) iso (cal(O)_k quo (p)) quo (frak(p) quo (p))
  $
  and hence it is enough to check that $frak(p)$ is prime in $FF_p [x] quo (x^3 - 5)$, which is equivalent to checking that it is generated by an irreducible polynomial, this gives us the following prime decompositions.
  $
    (2) = (2,alpha+1)(2, alpha^2 + alpha + 1)\
    (3) = (3,alpha+1)^3\
    (5) = (5,alpha)^3\
    (7) = (7)\
    (11) = (11, alpha+3)(11, alpha^2 + 3 alpha + 9)\
    (13) = (13, alpha+2)(13, alpha + 5)(13, alpha + 6)\
  $
+ The only decomposition that does not occur in this list is $(p) = X^2 Y$ for $X,Y$ prime ideals, let us assume that such a decomposition exists, then in our framework $X$ and $Y$ correspond to ideals of $FF_p [x] quo (x^3-5)$ which are all of degree 1, so are generated by linear elements. In other words, $X = (x - a), Y = (x - b)$. We thus have
  $
    (x-a)^2 (x-b)
    =
    (x^2 - 2 a x + a^2) (x - b)
    =
    x^3 - 2 a x^2 - b x^2 + a^2 x + 2 a b x - a^2 b
    \
    = x^3 + (-2a - b) x^2 + (a^2 + 2 a b) x - a^2 b
  $
  and so we have the following equivalences
  $
    -2a - b equiv 0 mod p
    quad
    a(a + 2b) equiv 0 mod p
  $
  and so we can now solve these equivalences. If $a equiv 0$ then we have $b equiv 0$ so we do not have distinct roots. We can thus assume that $a$ is invertible so $a + 2b equiv 0 mod p$ and also $2 a + b equiv 0 mod p$ and thus we have $a + 2 b - (4 a + 2 b) = - 3 a equiv 0 mod p$ so $a equiv 0$ and then again $b equiv 0$. We thus have a full contradiction and so such a decomposition cannot exist.
+ We set $alpha = root(3,10)$ and consider the number field $K = QQ(alpha)$, note that the following is an integral element of $cal(O)_K$
  $
    beta = (1 + alpha + alpha^2)/3
  $
  because
  $
    beta^3 - beta^2 - 3 beta - 3 = 0
  $
  and we have that the trace matrix looks like
  $
    mat(3,1,7;1,7,19;7,19,43)
  $
  so the discriminant is $Delta(1,beta,beta^2) = -300$, which factors as $-5^2 dot 3 dot 2^2$. But we know that the true discriminant shares the 2 and 5 factors because $x^3 - 10$ is Eisenstein with $p = 2$ and $p = 5$. We thus have $cal(O)_k = ZZ[x] quo (x^3 - x^2 - 3x - 3)$. Now in this ring we consider the prime ideal $(3)$ and we find using our usual technique that $x^3 - x^2 - 3x - 3 equiv x^2 (x - 1) mod 3$ so
  $
    (3) = (3, beta)^2 (3, beta - 1)
  $
  is the prime decomposition we were missing.

= Question
== Statement
For every ideal $frak(p)$ of $cal(O)_K$, show that there exists an order $A = ZZ[theta] seq cal(O)_K$ such that its conductor is coprime to $frak(p)$.
== Solution
Set $(p) = ZZ sect frak(p)$ and we consider the extension $(cal(O)_K)_frak(p) seq (cal(O)_K)_((p))$, since $(cal(O)_K)_((p))$ is finitely generated as a $ZZ_((p))$ module we get that $(cal(O)_K)_frak(p)$ is as well.

Now $(cal(O)_K)_frak(p)$ is a local ring so all its ideals are of the form $(pi^n)$ where $pi$ is a uniformizing element. Now $(cal(O)_K)_frak(p) quo (p)$ is an extension of $(cal(O)_K)_(frak(p)) quo frak(p)$ which is a field isomorphic $FF_p [theta]$ for some $theta$, which is importantly a separable extension. As an extension, $(cal(O)_K)_frak(p) quo (p)$, must then be generated by ${ theta^i pi^j : i,j <= N }$ for some $N$. Thus if we want to show that $(cal(O)_K)_frak(p) quo (p)$ is monogenic generated by $theta$, it is enough to show that we can write some uniformizing element $pi$ as a polynomial in $theta$, that is $pi = f(theta)$. We will choose $f$ to be the minimal polynomial of $tilde(theta)$ in $(cal(O)_K)_frak(p) quo frak(p)$, by definition we have $f(theta) in frak(p)$. Assume now that it is not uniformizing, then $f(theta) in frak(p)^2$. Now we have for any uniformizing element $pi$
$
  f(theta + pi) = f(theta) + pi f'(theta) + pi^2 b
$
for some $b in (cal(O)_K)_frak(p) quo (p)$. Now by assumption, both $f(theta)$ and $pi^2 b$ are in $frak(p)^2$, and since the field is separable we know that $f'(tilde(theta)) != 0$ and so $f'(theta) in.not frak(p)$ so $pi f'(theta) in frak(p) backslash frak(p)^2$. Thus $f(theta + pi) in frak(p) backslash frak(p)^2$ and is thus a uniformizing element.

Now finally, $1,theta,theta^2,...,theta^M$ generates $(cal(O)_K)_frak(p) quo (p)$ as a $ZZ_((p))$ module so we have by Nakayama's lemma that for some element $ov(theta)$ with image $theta$, $1,ov(theta),ov(theta)^2,...,ov(theta)^M$ generates $(cal(O)_K)_(frak(p))$ as a $ZZ_((p))$ module.

Now by cancelling out the denominators we have that for some $n in.not (p)$, we have $(n)cal(O)_K seq  ZZ[ov(theta)]$ so since $n in.not (p)$ we get that $(n) cal(O)_K$ is coprime to $frak(p)$.

= Question
== Statement
Let $L_1, L_2$ be finite extensions of a number field $K$. If a prime ideal $frak(p)$ of $cal(O)_K$ is split completely in $L_1,L_2$, then it is so in the composition $L_1 L_2$.
== Solution
Let $F$ be any normal extension containing $L_1 L_2$, then let $frak(q)$ be any prime lying over $frak(p)$. Let now, $D_frak(q)$ be the decomposition subgroup of $frak(q)$, then we consider $F^(D_frak(q))$, the elements of $F$ fixed under $I_frak(q)$. As we see in Marcus's book, the field $F^(D_frak(q))$ is the largest subfield of $F$ in which every $frak(p)$ completely splits, but then since $frak(p)$ completely splits in $L_1$ and in $L_2$ then we must have that $L_1$ and $L_2$ are subfields of $F^(D_frak(q))$. Thus $L_1 L_2$ is also a subfield of $F^(D_frak(q))$ and thus $frak(p)$ splits in $L_1 L_2$.

= Question
== Statement
Let $L quo K$ be a finite Galois extension of number fields with non-cyclic Galois group. Show that there are only finitely many non-split primes in $cal(O)_K$.
== Solution
Let $(p)$ be a non-split prime in $cal(O)_K$, then either $(p)$ is ramified or inert, so since there are only finitely many ramified primes then let us assume there are infinitely many inert primes.
For each inert prime $(p)$ we have $D_((p)) iso Gal(L quo K)$ which is a cyclic group.




#counter(heading).step()
= Question
== Statement
Show that for every finite abelian group $G$ there exists a Galois extension $K$ of $QQ$ such that $Gal(K quo QQ) iso G$.
== Solution
We know from class that $Gal(K quo QQ) = (ZZ quo n ZZ)^times$ for $K = QQ(zeta_n)$ where $zeta_n$ is the $n$-th root of unity. Now also from class we know that $(ZZ quo p ZZ)^times iso ZZ quo (p-1) ZZ$ for any prime $p$.

Next we recall that every finite abelian group $G$ has the form
$
  G iso (ZZ quo n_1 ZZ) times (ZZ quo n_2 ZZ) times dots.c times (ZZ quo n_k ZZ).
$
Now fix any given $n_i$ and recall that by Dirichlet's Theorem there are infinitely many primes satisfying $p = 1 mod n_i$ so pick one of these primes and denote it $p_i$, with $p_i - 1 = m_i n_i$ for some integer $m_i$. We can pick $p_i$ such that they are all distinct We thus get that
$
  G seq (ZZ quo (p_1-1) ZZ) times (ZZ quo (p_2-1) ZZ) times dots.c times (ZZ quo (p_k - 1) ZZ).
$
now the group on the right is exactly the group of units for $ZZ quo (p_1 p_2 p_3 ... p_k) ZZ$ so we get that 
$
  G seq ZZ quo (p_1 p_2 ... p_k) ZZ iso Gal(QQ(zeta_(p_1 p_2... p_k)) quo QQ)
$
now for an abelian group any subgroup is also a quotient, which you can easily see by Chinese Remainder Theorem.
Now by the fundamental theorem of Galois theory we know that this quotient then corresponds to some subfield of $QQ(zeta_(p_1 ... p_k))$ and thus that subfield is an extension of $QQ$ with the desired property.

= Question
== Statement
Show that every quadratic field is a subfield of some cyclotomic field.
== Solution
Let $m$ be some square free integer and let $m = plus.minus p_1 dots.c p_n$ be the prime decomposition of $m$, with all prime distinct because it is square free, we then have $sqrt(m) = sqrt(plus.minus 1) sqrt(p_1) dots.c sqrt(p_n)$ so it is enough to show that $sqrt(p)$ is contained in $QQ[zeta_n]$ for some $n$.

To that end first assume that $p$ is an odd prime, then we have that $Delta_K = p^(p-2)$ where $K = QQ[zeta_p]$ which we saw in class. But we also know from class that
$
  Delta_K = product_(1 <= i < j <= p) (zeta_p^(i-1) - zeta_p^(j-1))^2
$
and so
$
  product_(1 <= i < j <= p) (zeta_p^(i-1) - zeta_p^(j-1)) = plus.minus p^((p-2)/2) = plus.minus p^((p-3)/2) sqrt(p).
$
Now $p^((p-3)/2)$ is an integer and thus invertible in $QQ$ and so $sqrt(p)$ is in $QQ[zeta_p]$.

Now if $p = 2$ then we have $sqrt(2) in QQ[zeta_8]$ because $zeta_8 = sqrt(2)/2 + i sqrt(2)/2$, this also contains $sqrt(-1)$. Thus we $QQ[zeta_(8 m)]$ will always contain $sqrt(m)$ and so we are done.
